apiVersion: v1
kind: Service
metadata:
  name: authguard-svc
  namespace: authguard
spec:
  type: NodePort
  selector:
    app: authguard
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000 # Можно оставить автоподбор
