apiVersion: apps/v1
kind: Deployment
metadata:
  name: authguard
  namespace: authguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authguard
  template:
    metadata:
      labels:
        app: authguard
    spec:
      containers:
        - name: authguard
          image: feylog/authguard:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: authguard-config
            - secretRef:
                name: authguard-secret
          env:
            # DATABASE_URL со ссылкой на сервис postgres-svc
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-svc:5432/authguard"
