apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: authguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authguard-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: authguard
          volumes:
            - name: postgres-data
              persistentVolumeClaim:
                claimName: postgres-pvc
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
